// prisma/seed.ts

import { PrismaClient } from '@prisma/client'; // Import enums from Prisma client
import * as bcrypt from 'bcryptjs';
const prisma = new PrismaClient();

async function main() {
  // Create seed data for teachers
  //   const teacher1 = await prisma.teacher.create({
  //     data: {
  //       educational_level: 'ماجستير',
  //       university_name: 'جامعة دمشق',
  //       college_name: 'كلية التربية',
  //       first_name: 'أحمد',
  //       last_name: 'الخطيب',
  //       birth_date: new Date('1980-05-10'),
  //       mobile_phone_number: '0998765432',
  //       job_role: 'مدرس أول',
  //       workplace_name: 'مركز التعليم المتقدم',
  //       is_mojaz: true,
  //       is_working: true,
  //       current_residence_address_area: 'باب توما',
  //       current_residence_address_street: 'شارع العابد',
  //       current_residence_address_building: 'البناء رقم 4',
  //     },
  //   });

  //   const teacher2 = await prisma.teacher.create({
  //     data: {
  //       educational_level: 'بكالوريوس',
  //       university_name: 'جامعة حلب',
  //       college_name: 'كلية الآداب',
  //       first_name: 'ليلى',
  //       last_name: 'العلي',
  //       birth_date: new Date('1985-09-15'),
  //       mobile_phone_number: '0987654321',
  //       job_role: 'مدرسة',
  //       workplace_name: 'مدرسة الأمل',
  //       is_mojaz: true,
  //       is_working: false,
  //       current_residence_address_area: 'المزة',
  //       current_residence_address_street: 'شارع الثورة',
  //       current_residence_address_building: 'البناء رقم 12',
  //     },
  //   });

  //   // Create seed data for groups
  //   const group1 = await prisma.group.create({
  //     data: {
  //       title: 'مجموعة النور',
  //       teacherId: teacher1.id,
  //     },
  //   });

  //   const group2 = await prisma.group.create({
  //     data: {
  //       title: 'مجموعة النجاح',
  //       teacherId: teacher2.id,
  //     },
  //   });

  // Create seed data for students with nested relation to Group
  const studentsData = [
    {
      first_name: 'محمد',
      last_name: 'الأسعد',
      birth_date: new Date('2012-03-15'),
      current_mosque_name: 'مسجد الرحمة',
      educational_class: 6,
      student_mobile: '0945123456',
      school: 'مدرسة اليرموك الابتدائية',
      in_another_mosque: false,
      father_name: 'عمر الأسعد',
      father_phone_number: '0954332101',
      mother_name: 'سعاد الأسعد',
      current_residence_address_area: 'القصاع',
      current_residence_address_street: 'شارع الزهور',
      current_residence_address_building: 'البناء رقم 7',
    },
    {
      first_name: 'أحمد',
      last_name: 'الخالد',
      birth_date: new Date('2011-07-22'),
      current_mosque_name: 'مسجد الفاروق',
      educational_class: 7,
      student_mobile: '0945112233',
      school: 'مدرسة النهضة الابتدائية',
      in_another_mosque: false,
      father_name: 'خالد الخالد',
      father_phone_number: '0954445566',
      mother_name: 'فاطمة الخالد',
      current_residence_address_area: 'المزة',
      current_residence_address_street: 'شارع النصر',
      current_residence_address_building: 'البناء رقم 12',
    },
    {
      first_name: 'علي',
      last_name: 'الحسين',
      birth_date: new Date('2010-11-05'),
      current_mosque_name: 'مسجد النور',
      educational_class: 8,
      student_mobile: '0945667788',
      school: 'مدرسة الفتح الإعدادية',
      in_another_mosque: true,
      father_name: 'حسين الحسين',
      father_phone_number: '0954889900',
      mother_name: 'ليلى الحسين',
      current_residence_address_area: 'الشاغور',
      current_residence_address_street: 'شارع القلمون',
      current_residence_address_building: 'البناء رقم 3',
    },
    {
      first_name: 'يوسف',
      last_name: 'العباس',
      birth_date: new Date('2013-02-18'),
      current_mosque_name: 'مسجد السلام',
      educational_class: 6,
      student_mobile: '0945123789',
      school: 'مدرسة الأندلس الابتدائية',
      in_another_mosque: false,
      father_name: 'عباس العباس',
      father_phone_number: '0954123456',
      mother_name: 'منى العباس',
      current_residence_address_area: 'الميدان',
      current_residence_address_street: 'شارع العابد',
      current_residence_address_building: 'البناء رقم 9',
    },
    {
      first_name: 'خالد',
      last_name: 'المنصور',
      birth_date: new Date('2012-09-30'),
      current_mosque_name: 'مسجد التقوى',
      educational_class: 7,
      student_mobile: '0945234567',
      school: 'مدرسة الإيمان الابتدائية',
      in_another_mosque: false,
      father_name: 'منصور المنصور',
      father_phone_number: '0954345678',
      mother_name: 'هناء المنصور',
      current_residence_address_area: 'القدم',
      current_residence_address_street: 'شارع الجسر',
      current_residence_address_building: 'البناء رقم 5',
    },
    {
      first_name: 'محمود',
      last_name: 'الغنيم',
      birth_date: new Date('2011-04-12'),
      current_mosque_name: 'مسجد الإخلاص',
      educational_class: 8,
      student_mobile: '0945345678',
      school: 'مدرسة الفلاح الإعدادية',
      in_another_mosque: true,
      father_name: 'غنيم الغنيم',
      father_phone_number: '0954456789',
      mother_name: 'سارة الغنيم',
      current_residence_address_area: 'الصالحية',
      current_residence_address_street: 'شارع العروبة',
      current_residence_address_building: 'البناء رقم 8',
    },
    {
      first_name: 'عمر',
      last_name: 'الزعيم',
      birth_date: new Date('2010-12-25'),
      current_mosque_name: 'مسجد القدس',
      educational_class: 9,
      student_mobile: '0945456789',
      school: 'مدرسة النجاح الإعدادية',
      in_another_mosque: false,
      father_name: 'زعيم الزعيم',
      father_phone_number: '0954567890',
      mother_name: 'رنا الزعيم',
      current_residence_address_area: 'الركن',
      current_residence_address_street: 'شارع القادسية',
      current_residence_address_building: 'البناء رقم 10',
    },
    {
      first_name: 'باسل',
      last_name: 'الرفاعي',
      birth_date: new Date('2013-06-14'),
      current_mosque_name: 'مسجد الفتح',
      educational_class: 6,
      student_mobile: '0945567890',
      school: 'مدرسة السلام الابتدائية',
      in_another_mosque: false,
      father_name: 'رفاعي الرفاعي',
      father_phone_number: '0954678901',
      mother_name: 'لمى الرفاعي',
      current_residence_address_area: 'العدوي',
      current_residence_address_street: 'شارع العريض',
      current_residence_address_building: 'البناء رقم 4',
    },
    {
      first_name: 'سامي',
      last_name: 'السعيد',
      birth_date: new Date('2012-08-19'),
      current_mosque_name: 'مسجد النصر',
      educational_class: 7,
      student_mobile: '0945678901',
      school: 'مدرسة الأمل الابتدائية',
      in_another_mosque: false,
      father_name: 'سعيد السعيد',
      father_phone_number: '0954789012',
      mother_name: 'ناديا السعيد',
      current_residence_address_area: 'القابون',
      current_residence_address_street: 'شارع الفردوس',
      current_residence_address_building: 'البناء رقم 6',
    },
    {
      first_name: 'طارق',
      last_name: 'العبيدي',
      birth_date: new Date('2011-03-07'),
      current_mosque_name: 'مسجد الإيمان',
      educational_class: 8,
      student_mobile: '0945789012',
      school: 'مدرسة الفاروق الإعدادية',
      in_another_mosque: true,
      father_name: 'عبيدي العبيدي',
      father_phone_number: '0954890123',
      mother_name: 'مريم العبيدي',
      current_residence_address_area: 'المزرعة',
      current_residence_address_street: 'شارع الوحدة',
      current_residence_address_building: 'البناء رقم 11',
    },
    {
      first_name: 'ناصر',
      last_name: 'الغالي',
      birth_date: new Date('2010-10-11'),
      current_mosque_name: 'مسجد العزيز',
      educational_class: 9,
      student_mobile: '0945890123',
      school: 'مدرسة النهضة الإعدادية',
      in_another_mosque: false,
      father_name: 'غالي الغالي',
      father_phone_number: '0954901234',
      mother_name: 'سهام الغالي',
      current_residence_address_area: 'المالكي',
      current_residence_address_street: 'شارع الجميل',
      current_residence_address_building: 'البناء رقم 13',
    },
    {
      first_name: 'رامي',
      last_name: 'الهادي',
      birth_date: new Date('2013-05-09'),
      current_mosque_name: 'مسجد الهدى',
      educational_class: 6,
      student_mobile: '0945901234',
      school: 'مدرسة الفلاح الابتدائية',
      in_another_mosque: false,
      father_name: 'هادي الهادي',
      father_phone_number: '0955012345',
      mother_name: 'أمل الهادي',
      current_residence_address_area: 'القدم',
      current_residence_address_street: 'شارع السلام',
      current_residence_address_building: 'البناء رقم 2',
    },
    {
      first_name: 'فادي',
      last_name: 'الرحيم',
      birth_date: new Date('2012-01-23'),
      current_mosque_name: 'مسجد الرحمن',
      educational_class: 7,
      student_mobile: '0945012345',
      school: 'مدرسة الإيمان الابتدائية',
      in_another_mosque: false,
      father_name: 'رحيم الرحيم',
      father_phone_number: '0955123456',
      mother_name: 'نور الرحيم',
      current_residence_address_area: 'الميدان',
      current_residence_address_street: 'شارع العابد',
      current_residence_address_building: 'البناء رقم 7',
    },
    {
      first_name: 'وسام',
      last_name: 'المنصور',
      birth_date: new Date('2011-07-14'),
      current_mosque_name: 'مسجد الفاروق',
      educational_class: 8,
      student_mobile: '0945123456',
      school: 'مدرسة النهضة الإعدادية',
      in_another_mosque: true,
      father_name: 'منصور المنصور',
      father_phone_number: '0955234567',
      mother_name: 'هناء المنصور',
      current_residence_address_area: 'الشاغور',
      current_residence_address_street: 'شارع القلمون',
      current_residence_address_building: 'البناء رقم 3',
    },
    {
      first_name: 'ياسر',
      last_name: 'الغنيم',
      birth_date: new Date('2010-12-30'),
      current_mosque_name: 'مسجد النور',
      educational_class: 9,
      student_mobile: '0945234567',
      school: 'مدرسة الفتح الإعدادية',
      in_another_mosque: false,
      father_name: 'غنيم الغنيم',
      father_phone_number: '0955345678',
      mother_name: 'سارة الغنيم',
      current_residence_address_area: 'الصالحية',
      current_residence_address_street: 'شارع العروبة',
      current_residence_address_building: 'البناء رقم 8',
    },
    {
      first_name: 'مازن',
      last_name: 'الزعيم',
      birth_date: new Date('2013-03-18'),
      current_mosque_name: 'مسجد القدس',
      educational_class: 6,
      student_mobile: '0945345678',
      school: 'مدرسة النجاح الابتدائية',
      in_another_mosque: false,
      father_name: 'زعيم الزعيم',
      father_phone_number: '0955456789',
      mother_name: 'رنا الزعيم',
      current_residence_address_area: 'الركن',
      current_residence_address_street: 'شارع القادسية',
      current_residence_address_building: 'البناء رقم 10',
    },
    {
      first_name: 'جمال',
      last_name: 'الرفاعي',
      birth_date: new Date('2012-06-22'),
      current_mosque_name: 'مسجد الفتح',
      educational_class: 7,
      student_mobile: '0945456789',
      school: 'مدرسة السلام الابتدائية',
      in_another_mosque: false,
      father_name: 'رفاعي الرفاعي',
      father_phone_number: '0955567890',
      mother_name: 'لمى الرفاعي',
      current_residence_address_area: 'العدوي',
      current_residence_address_street: 'شارع العريض',
      current_residence_address_building: 'البناء رقم 4',
    },
    {
      first_name: 'رامي',
      last_name: 'السعيد',
      birth_date: new Date('2011-09-15'),
      current_mosque_name: 'مسجد النصر',
      educational_class: 8,
      student_mobile: '0945567890',
      school: 'مدرسة الأمل الإعدادية',
      in_another_mosque: true,
      father_name: 'سعيد السعيد',
      father_phone_number: '0955678901',
      mother_name: 'ناديا السعيد',
      current_residence_address_area: 'القابون',
      current_residence_address_street: 'شارع الفردوس',
      current_residence_address_building: 'البناء رقم 6',
    },
    {
      first_name: 'عبد الله',
      last_name: 'العبيدي',
      birth_date: new Date('2010-04-27'),
      current_mosque_name: 'مسجد الإيمان',
      educational_class: 9,
      student_mobile: '0945678901',
      school: 'مدرسة الفاروق الإعدادية',
      in_another_mosque: false,
      father_name: 'عبيدي العبيدي',
      father_phone_number: '0955789012',
      mother_name: 'مريم العبيدي',
      current_residence_address_area: 'المزرعة',
      current_residence_address_street: 'شارع الوحدة',
      current_residence_address_building: 'البناء رقم 11',
    },
    {
      first_name: 'مصطفى',
      last_name: 'الغالي',
      birth_date: new Date('2013-08-10'),
      current_mosque_name: 'مسجد العزيز',
      educational_class: 6,
      student_mobile: '0945789012',
      school: 'مدرسة النهضة الابتدائية',
      in_another_mosque: false,
      father_name: 'غالي الغالي',
      father_phone_number: '0955890123',
      mother_name: 'سهام الغالي',
      current_residence_address_area: 'المالكي',
      current_residence_address_street: 'شارع الجميل',
      current_residence_address_building: 'البناء رقم 13',
    },
    {
      first_name: 'أنس',
      last_name: 'الهادي',
      birth_date: new Date('2012-11-03'),
      current_mosque_name: 'مسجد الهدى',
      educational_class: 7,
      student_mobile: '0945890123',
      school: 'مدرسة الفلاح الابتدائية',
      in_another_mosque: false,
      father_name: 'هادي الهادي',
      father_phone_number: '0955901234',
      mother_name: 'أمل الهادي',
      current_residence_address_area: 'القدم',
      current_residence_address_street: 'شارع السلام',
      current_residence_address_building: 'البناء رقم 2',
    },
    {
      first_name: 'عبد الرحمن',
      last_name: 'الرحيم',
      birth_date: new Date('2011-02-14'),
      current_mosque_name: 'مسجد الرحمن',
      educational_class: 8,
      student_mobile: '0945901234',
      school: 'مدرسة الإيمان الإعدادية',
      in_another_mosque: true,
      father_name: 'رحيم الرحيم',
      father_phone_number: '0955012345',
      mother_name: 'نور الرحيم',
      current_residence_address_area: 'الميدان',
      current_residence_address_street: 'شارع العابد',
      current_residence_address_building: 'البناء رقم 7',
    },
    {
      first_name: 'زياد',
      last_name: 'المنصور',
      birth_date: new Date('2010-07-29'),
      current_mosque_name: 'مسجد الفاروق',
      educational_class: 9,
      student_mobile: '0945012345',
      school: 'مدرسة النهضة الإعدادية',
      in_another_mosque: false,
      father_name: 'منصور المنصور',
      father_phone_number: '0955123456',
      mother_name: 'هناء المنصور',
      current_residence_address_area: 'الشاغور',
      current_residence_address_street: 'شارع القلمون',
      current_residence_address_building: 'البناء رقم 3',
    },
    {
      first_name: 'ماهر',
      last_name: 'الغنيم',
      birth_date: new Date('2013-04-05'),
      current_mosque_name: 'مسجد النور',
      educational_class: 6,
      student_mobile: '0945123456',
      school: 'مدرسة الفتح الابتدائية',
      in_another_mosque: false,
      father_name: 'غنيم الغنيم',
      father_phone_number: '0955234567',
      mother_name: 'سارة الغنيم',
      current_residence_address_area: 'الصالحية',
      current_residence_address_street: 'شارع العروبة',
      current_residence_address_building: 'البناء رقم 8',
    },
    {
      first_name: 'وليد',
      last_name: 'الزعيم',
      birth_date: new Date('2012-09-12'),
      current_mosque_name: 'مسجد القدس',
      educational_class: 7,
      student_mobile: '0945234567',
      school: 'مدرسة النجاح الابتدائية',
      in_another_mosque: false,
      father_name: 'زعيم الزعيم',
      father_phone_number: '0955345678',
      mother_name: 'رنا الزعيم',
      current_residence_address_area: 'الركن',
      current_residence_address_street: 'شارع القادسية',
      current_residence_address_building: 'البناء رقم 10',
    },
    {
      first_name: 'سعيد',
      last_name: 'الرفاعي',
      birth_date: new Date('2011-12-20'),
      current_mosque_name: 'مسجد الفتح',
      educational_class: 8,
      student_mobile: '0945345678',
      school: 'مدرسة السلام الإعدادية',
      in_another_mosque: true,
      father_name: 'رفاعي الرفاعي',
      father_phone_number: '0955456789',
      mother_name: 'لمى الرفاعي',
      current_residence_address_area: 'العدوي',
      current_residence_address_street: 'شارع العريض',
      current_residence_address_building: 'البناء رقم 4',
    },
    {
      first_name: 'عمار',
      last_name: 'السعيد',
      birth_date: new Date('2010-05-17'),
      current_mosque_name: 'مسجد النصر',
      educational_class: 9,
      student_mobile: '0945456789',
      school: 'مدرسة الأمل الإعدادية',
      in_another_mosque: false,
      father_name: 'سعيد السعيد',
      father_phone_number: '0955567890',
      mother_name: 'ناديا السعيد',
      current_residence_address_area: 'القابون',
      current_residence_address_street: 'شارع الفردوس',
      current_residence_address_building: 'البناء رقم 6',
    },
    {
      first_name: 'فارس',
      last_name: 'العبيدي',
      birth_date: new Date('2013-01-08'),
      current_mosque_name: 'مسجد الإيمان',
      educational_class: 6,
      student_mobile: '0945567890',
      school: 'مدرسة الفاروق الابتدائية',
      in_another_mosque: false,
      father_name: 'عبيدي العبيدي',
      father_phone_number: '0955678901',
      mother_name: 'مريم العبيدي',
      current_residence_address_area: 'المزرعة',
      current_residence_address_street: 'شارع الوحدة',
      current_residence_address_building: 'البناء رقم 11',
    },
    {
      first_name: 'نور',
      last_name: 'الغالي',
      birth_date: new Date('2012-04-21'),
      current_mosque_name: 'مسجد العزيز',
      educational_class: 7,
      student_mobile: '0945678901',
      school: 'مدرسة النهضة الابتدائية',
      in_another_mosque: false,
      father_name: 'غالي الغالي',
      father_phone_number: '0955789012',
      mother_name: 'سهام الغالي',
      current_residence_address_area: 'المالكي',
      current_residence_address_street: 'شارع الجميل',
      current_residence_address_building: 'البناء رقم 13',
    },
    {
      first_name: 'هشام',
      last_name: 'الهادي',
      birth_date: new Date('2011-08-16'),
      current_mosque_name: 'مسجد الهدى',
      educational_class: 8,
      student_mobile: '0945789012',
      school: 'مدرسة الفلاح الإعدادية',
      in_another_mosque: true,
      father_name: 'هادي الهادي',
      father_phone_number: '0955890123',
      mother_name: 'أمل الهادي',
      current_residence_address_area: 'القدم',
      current_residence_address_street: 'شارع السلام',
      current_residence_address_building: 'البناء رقم 2',
    },
    {
      first_name: 'صلاح',
      last_name: 'الرحيم',
      birth_date: new Date('2010-11-29'),
      current_mosque_name: 'مسجد الرحمن',
      educational_class: 9,
      student_mobile: '0945890123',
      school: 'مدرسة الإيمان الإعدادية',
      in_another_mosque: false,
      father_name: 'رحيم الرحيم',
      father_phone_number: '0955901234',
      mother_name: 'نور الرحيم',
      current_residence_address_area: 'الميدان',
      current_residence_address_street: 'شارع العابد',
      current_residence_address_building: 'البناء رقم 7',
    },
    {
      first_name: 'رائد',
      last_name: 'المنصور',
      birth_date: new Date('2013-07-04'),
      current_mosque_name: 'مسجد الفاروق',
      educational_class: 6,
      student_mobile: '0945901234',
      school: 'مدرسة النهضة الابتدائية',
      in_another_mosque: false,
      father_name: 'منصور المنصور',
      father_phone_number: '0955012345',
      mother_name: 'هناء المنصور',
      current_residence_address_area: 'الشاغور',
      current_residence_address_street: 'شارع القلمون',
      current_residence_address_building: 'البناء رقم 3',
    },
    {
      first_name: 'مروان',
      last_name: 'الغنيم',
      birth_date: new Date('2012-10-13'),
      current_mosque_name: 'مسجد النور',
      educational_class: 7,
      student_mobile: '0945012345',
      school: 'مدرسة الفتح الابتدائية',
      in_another_mosque: false,
      father_name: 'غنيم الغنيم',
      father_phone_number: '0955123456',
      mother_name: 'سارة الغنيم',
      current_residence_address_area: 'الصالحية',
      current_residence_address_street: 'شارع العروبة',
      current_residence_address_building: 'البناء رقم 8',
    },
    {
      first_name: 'عبد العزيز',
      last_name: 'الزعيم',
      birth_date: new Date('2011-03-26'),
      current_mosque_name: 'مسجد القدس',
      educational_class: 8,
      student_mobile: '0945123456',
      school: 'مدرسة النجاح الإعدادية',
      in_another_mosque: true,
      father_name: 'زعيم الزعيم',
      father_phone_number: '0955234567',
      mother_name: 'رنا الزعيم',
      current_residence_address_area: 'الركن',
      current_residence_address_street: 'شارع القادسية',
      current_residence_address_building: 'البناء رقم 10',
    },
    {
      first_name: 'إيهاب',
      last_name: 'الرفاعي',
      birth_date: new Date('2010-06-19'),
      current_mosque_name: 'مسجد الفتح',
      educational_class: 9,
      student_mobile: '0945234567',
      school: 'مدرسة السلام الإعدادية',
      in_another_mosque: false,
      father_name: 'رفاعي الرفاعي',
      father_phone_number: '0955345678',
      mother_name: 'لمى الرفاعي',
      current_residence_address_area: 'العدوي',
      current_residence_address_street: 'شارع العريض',
      current_residence_address_building: 'البناء رقم 4',
    },
    {
      first_name: 'عبد الكريم',
      last_name: 'السعيد',
      birth_date: new Date('2013-09-02'),
      current_mosque_name: 'مسجد النصر',
      educational_class: 6,
      student_mobile: '0945345678',
      school: 'مدرسة الأمل الابتدائية',
      in_another_mosque: false,
      father_name: 'سعيد السعيد',
      father_phone_number: '0955456789',
      mother_name: 'ناديا السعيد',
      current_residence_address_area: 'القابون',
      current_residence_address_street: 'شارع الفردوس',
      current_residence_address_building: 'البناء رقم 6',
    },
    {
      first_name: 'عماد',
      last_name: 'العبيدي',
      birth_date: new Date('2012-12-11'),
      current_mosque_name: 'مسجد الإيمان',
      educational_class: 7,
      student_mobile: '0945456789',
      school: 'مدرسة الفاروق الابتدائية',
      in_another_mosque: false,
      father_name: 'عبيدي العبيدي',
      father_phone_number: '0955567890',
      mother_name: 'مريم العبيدي',
      current_residence_address_area: 'المزرعة',
      current_residence_address_street: 'شارع الوحدة',
      current_residence_address_building: 'البناء رقم 11',
    },
    {
      first_name: 'عبد الرحمن',
      last_name: 'الغالي',
      birth_date: new Date('2011-05-24'),
      current_mosque_name: 'مسجد العزيز',
      educational_class: 8,
      student_mobile: '0945567890',
      school: 'مدرسة النهضة الإعدادية',
      in_another_mosque: true,
      father_name: 'غالي الغالي',
      father_phone_number: '0955678901',
      mother_name: 'سهام الغالي',
      current_residence_address_area: 'المالكي',
      current_residence_address_street: 'شارع الجميل',
      current_residence_address_building: 'البناء رقم 13',
    },
    {
      first_name: 'عبد الله',
      last_name: 'الهادي',
      birth_date: new Date('2010-08-07'),
      current_mosque_name: 'مسجد الهدى',
      educational_class: 9,
      student_mobile: '0945678901',
      school: 'مدرسة الفلاح الإعدادية',
      in_another_mosque: false,
      father_name: 'هادي الهادي',
      father_phone_number: '0955789012',
      mother_name: 'أمل الهادي',
      current_residence_address_area: 'القدم',
      current_residence_address_street: 'شارع السلام',
      current_residence_address_building: 'البناء رقم 2',
    },
    {
      first_name: 'عبد الحكيم',
      last_name: 'الرحيم',
      birth_date: new Date('2013-02-28'),
      current_mosque_name: 'مسجد الرحمن',
      educational_class: 6,
      student_mobile: '0945789012',
      school: 'مدرسة الإيمان الابتدائية',
      in_another_mosque: false,
      father_name: 'رحيم الرحيم',
      father_phone_number: '0955890123',
      mother_name: 'نور الرحيم',
      current_residence_address_area: 'الميدان',
      current_residence_address_street: 'شارع العابد',
      current_residence_address_building: 'البناء رقم 7',
    },
  ];

  // const hashedPassword = await bcrypt.hash('password', 10);

  // create SUPER_ADMIN
  // await prisma.teacher.create({
  //   data: {
  //     mobile_phone_number: '0993544811',
  //     password: hashedPassword,
  //     role: 'SUPER_ADMIN',
  //   },
  // });

  // create new teacher

  // create new campaign
  // await prisma.campaign.create({
  //   data: {
  //     name: 'الدورة الصيفية 2024',
  //     studentsCount: 200,
  //     startTime: '',
  //     endTime: '',
  //     days: '',
  //   },
  // });

  for (const student of studentsData) {
    await prisma.student.create({
      data: student,
    });
  }

  console.log('Seed data created successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
